
import { Book, BookCondition, User, UserRole } from './types';

export const CURRENT_USER: User = {
  id: 'user_1',
  name: 'Alex Johnson',
  email: 'alex.j@mit.edu',
  college: 'MIT',
  branch: 'Computer Science',
  year: '2nd Year',
  role: UserRole.STUDENT,
  donationScore: 6,
  campusCoins: 12, // Initial coins
  phoneNumber: '9876543210',
  altPhoneNumber: '9012345678'
};

export const MOCK_BOOKS: Book[] = [
  {
    id: 'mit1',
    title: 'Introduction to Algorithms',
    author: 'Cormen, Leiserson, Rivest, Stein',
    condition: BookCondition.GOOD,
    isUrgent: true,
    isInstitutionDonated: false,
    donorId: 'user_2',
    college: 'MIT',
    branch: 'Computer Science',
    location: 'Main Library, Floor 2',
    pickupDate: '2024-10-24',
    pickupTime: '16:00',
    marketPrice: 1200,
    currentPrice: 450,
    imageUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=400&h=300',
    contactNumber: '9988776655'
  },
  {
    id: 'st1',
    title: 'Modern Operating Systems',
    author: 'Andrew S. Tanenbaum',
    condition: BookCondition.LIKE_NEW,
    isUrgent: true,
    isInstitutionDonated: false,
    donorId: 'user_5',
    college: 'Stanford',
    branch: 'Computer Science',
    location: 'Gates Building Lounge',
    pickupDate: '2024-10-25',
    pickupTime: '14:00',
    marketPrice: 900,
    currentPrice: 300,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'soc1',
    title: 'The Sociological Imagination',
    author: 'C. Wright Mills',
    condition: BookCondition.FAIR,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_25',
    college: 'MIT',
    branch: 'Social Sciences',
    location: 'Hayden Library',
    marketPrice: 450,
    currentPrice: 120,
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'blank2',
    title: 'Empty Sketchbook (2026 Edition)',
    author: 'Canson Premium',
    condition: BookCondition.NEW,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_8',
    college: 'MIT',
    branch: 'Architecture',
    location: 'Media Lab Basement',
    marketPrice: 850,
    currentPrice: 400,
    imageUrl: 'https://images.unsplash.com/photo-1519337265831-281ec6cc8514?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'hv1',
    title: 'Organic Chemistry',
    author: 'Jonathan Clayden',
    condition: BookCondition.NEW,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_6',
    college: 'Harvard',
    branch: 'Chemical Engineering',
    location: 'Science Center Basement',
    pickupDate: '2024-10-26',
    pickupTime: '11:00',
    marketPrice: 1500,
    currentPrice: 800,
    imageUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'du1',
    title: 'Macroeconomics',
    author: 'N. Gregory Mankiw',
    condition: BookCondition.GOOD,
    isUrgent: true,
    isInstitutionDonated: false,
    donorId: 'user_7',
    college: 'Delhi University',
    branch: 'Economics',
    location: 'North Campus Library',
    pickupDate: '2024-10-24',
    pickupTime: '15:30',
    marketPrice: 500,
    currentPrice: 0,
    imageUrl: 'https://images.unsplash.com/photo-1454165833767-027ffea9e7a7?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'mit2',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    condition: BookCondition.NEW,
    isUrgent: false,
    isInstitutionDonated: true,
    donorId: 'inst_1',
    college: 'MIT',
    branch: 'Software Engineering',
    location: 'Student Union Hub',
    pickupDate: 'Every Day',
    pickupTime: '09:00 - 18:00',
    marketPrice: 650,
    currentPrice: 0,
    imageUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'arch1',
    title: 'Architecture: Form, Space, & Order',
    author: 'Francis D.K. Ching',
    condition: BookCondition.LIKE_NEW,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_8',
    college: 'MIT',
    branch: 'Architecture',
    location: 'Design Studio 4',
    marketPrice: 1800,
    currentPrice: 750,
    imageUrl: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'med1',
    title: "Gray's Anatomy for Students",
    author: 'Richard Drake',
    condition: BookCondition.NEW,
    isUrgent: true,
    isInstitutionDonated: false,
    donorId: 'user_12',
    college: 'Stanford',
    branch: 'Medicine',
    location: 'Medical Quad',
    marketPrice: 3500,
    currentPrice: 1900,
    imageUrl: 'https://images.unsplash.com/photo-1576086213369-97a306dca664?auto=format&fit=crop&q=80&w=400&h=300'
  }
];
