
import { Book, BookCondition, User, UserRole } from './types';

export const CURRENT_USER: User = {
  id: 'user_1',
  name: 'Alex Johnson',
  email: 'alex.j@mit.edu',
  college: 'MIT',
  branch: 'Computer Science',
  year: '2nd Year',
  role: UserRole.STUDENT,
  donationScore: 6,
  campusCoins: 12, // Initial coins
  phoneNumber: '9876543210',
  altPhoneNumber: '9012345678'
};

export const MOCK_BOOKS: Book[] = [
  {
    id: 'mit1',
    title: 'Introduction to Algorithms',
    author: 'Cormen, Leiserson, Rivest, Stein',
    condition: BookCondition.GOOD,
    isUrgent: true,
    isInstitutionDonated: false,
    donorId: 'user_2',
    college: 'MIT',
    branch: 'Computer Science',
    location: 'Main Library, Floor 2',
    pickupDate: '2024-10-24',
    pickupTime: '16:00',
    marketPrice: 1200,
    currentPrice: 450,
    imageUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=400&h=300',
    contactNumber: '9988776655'
  },
  {
    id: 'st1',
    title: 'Modern Operating Systems',
    author: 'Andrew S. Tanenbaum',
    condition: BookCondition.LIKE_NEW,
    isUrgent: true,
    isInstitutionDonated: false,
    donorId: 'user_5',
    college: 'Stanford',
    branch: 'Computer Science',
    location: 'Gates Building Lounge',
    pickupDate: '2024-10-25',
    pickupTime: '14:00',
    marketPrice: 900,
    currentPrice: 300,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'hv1',
    title: 'Organic Chemistry',
    author: 'Jonathan Clayden',
    condition: BookCondition.NEW,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_6',
    college: 'Harvard',
    branch: 'Chemical Engineering',
    location: 'Science Center Basement',
    pickupDate: '2024-10-26',
    pickupTime: '11:00',
    marketPrice: 1500,
    currentPrice: 800,
    imageUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'du1',
    title: 'Macroeconomics',
    author: 'N. Gregory Mankiw',
    condition: BookCondition.GOOD,
    isUrgent: true,
    isInstitutionDonated: false,
    donorId: 'user_7',
    college: 'Delhi University',
    branch: 'Economics',
    location: 'North Campus Library',
    pickupDate: '2024-10-24',
    pickupTime: '15:30',
    marketPrice: 500,
    currentPrice: 0,
    imageUrl: 'https://images.unsplash.com/photo-1454165833767-027ffea9e7a7?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'mit2',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    condition: BookCondition.NEW,
    isUrgent: false,
    isInstitutionDonated: true,
    donorId: 'inst_1',
    college: 'MIT',
    branch: 'Software Engineering',
    location: 'Student Union Hub',
    pickupDate: 'Every Day',
    pickupTime: '09:00 - 18:00',
    marketPrice: 650,
    currentPrice: 0,
    imageUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'arch1',
    title: 'Architecture: Form, Space, & Order',
    author: 'Francis D.K. Ching',
    condition: BookCondition.LIKE_NEW,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_8',
    college: 'MIT',
    branch: 'Architecture',
    location: 'Design Studio 4',
    marketPrice: 1800,
    currentPrice: 750,
    imageUrl: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'med1',
    title: "Gray's Anatomy for Students",
    author: 'Richard Drake',
    condition: BookCondition.NEW,
    isUrgent: true,
    isInstitutionDonated: false,
    donorId: 'user_12',
    college: 'Stanford',
    branch: 'Medicine',
    location: 'Medical Quad',
    marketPrice: 3500,
    currentPrice: 1900,
    imageUrl: 'https://images.unsplash.com/photo-1576086213369-97a306dca664?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'phys1',
    title: 'Quantum Mechanics',
    author: 'David J. Griffiths',
    condition: BookCondition.GOOD,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_15',
    college: 'IIT Delhi',
    branch: 'Physics',
    location: 'LHC Lounge',
    marketPrice: 1100,
    currentPrice: 400,
    imageUrl: 'https://images.unsplash.com/photo-1636466484292-71048f06b224?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'law1',
    title: 'The Concept of Law',
    author: 'H.L.A. Hart',
    condition: BookCondition.GOOD,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_20',
    college: 'Oxford',
    branch: 'Law',
    location: 'Faculty of Law',
    marketPrice: 900,
    currentPrice: 200,
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'bio1',
    title: 'Campbell Biology',
    author: 'Lisa Urry',
    condition: BookCondition.LIKE_NEW,
    isUrgent: true,
    isInstitutionDonated: false,
    donorId: 'user_22',
    college: 'Stanford',
    branch: 'Biology',
    location: 'Clark Center',
    marketPrice: 2800,
    currentPrice: 1100,
    imageUrl: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'soc1',
    title: 'The Sociological Imagination',
    author: 'C. Wright Mills',
    condition: BookCondition.FAIR,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_25',
    college: 'MIT',
    branch: 'Social Sciences',
    location: 'Hayden Library',
    marketPrice: 450,
    currentPrice: 120,
    imageUrl: 'https://images.unsplash.com/photo-1507738911718-d6f7348858f6?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'lit1',
    title: 'English Literature: A Very Short Introduction',
    author: 'Jonathan Bate',
    condition: BookCondition.NEW,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_13',
    college: 'Harvard',
    branch: 'English Literature',
    location: 'Barker Center',
    marketPrice: 350,
    currentPrice: 180,
    imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'math1',
    title: 'Calculus',
    author: 'James Stewart',
    condition: BookCondition.GOOD,
    isUrgent: true,
    isInstitutionDonated: false,
    donorId: 'user_9',
    college: 'Stanford',
    branch: 'Mathematics',
    location: 'Sloan Math Corner',
    marketPrice: 2100,
    currentPrice: 950,
    imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'blank1',
    title: 'General Notebook (Blank)',
    author: 'N/A',
    condition: BookCondition.NEW,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_5',
    college: 'Stanford',
    branch: 'Stationery',
    location: 'Old Union',
    marketPrice: 200,
    currentPrice: 50,
    imageUrl: 'https://images.unsplash.com/photo-1543004629-ff569f872783?q=80&w=400&h=300&auto=format&fit=crop'
  },
  {
    id: 'blank2',
    title: 'Empty Sketchbook',
    author: 'Canson',
    condition: BookCondition.NEW,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_8',
    college: 'MIT',
    branch: 'Architecture',
    location: 'Media Lab Basement',
    marketPrice: 850,
    currentPrice: 400,
    imageUrl: 'https://images.unsplash.com/photo-1522066667558-417105940413?q=80&w=400&h=300&auto=format&fit=crop'
  },
  {
    id: 'psy1',
    title: 'Psychology',
    author: 'David Myers',
    condition: BookCondition.GOOD,
    isUrgent: false,
    isInstitutionDonated: true,
    donorId: 'inst_3',
    college: 'Stanford',
    branch: 'Psychology',
    location: 'Main Quad Office',
    marketPrice: 900,
    currentPrice: 0,
    imageUrl: 'https://images.unsplash.com/photo-1526232759583-26f17356555c?auto=format&fit=crop&q=80&w=400&h=300'
  },
  {
    id: 'hist1',
    title: 'A People\'s History of the United States',
    author: 'Howard Zinn',
    condition: BookCondition.FAIR,
    isUrgent: false,
    isInstitutionDonated: false,
    donorId: 'user_10',
    college: 'Harvard',
    branch: 'History',
    location: 'Widener Library',
    marketPrice: 650,
    currentPrice: 150,
    imageUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=400&h=300'
  }
];
